### ISSUE TITLE
Argo event sensor pods are crashing because of OOM

### ISSUE THREAD

**Issue by ShantanuKumar** [outerbounds/metaflow-tools#51]
While publishing 100s of argo events, we have seen sensor pods restarting few times after getting killed because of OOM.
Currently we don't see any way to modify the pod resource limit through the provided argo event helper chart.

This is the current allocated resource which we see on our cluster
``` yaml
Limits:
 cpu:     100m
 memory:  250Mi
Requests:
  cpu:     100m
  memory:  250Mi
```
