### ISSUE TITLE
metaflow-service doesn't have the MF_METADATA_DB_SSL_MODE envvar

### ISSUE THREAD

**Issue by bra-fsn** [outerbounds/metaflow-tools#75]
If you run
```
helm install --dry-run metaflow charts/metaflow
```

in this repo, you can see that some of the containers don't get the `MF_METADATA_DB_SSL_MODE`. For example the `run_goose.py` init container and the `metaflow-service`:

```yaml
      initContainers:
        - name: db-migrations
          image: "public.ecr.aws/outerbounds/metaflow_metadata_service:v2.4.13"
          command:
          - "/opt/latest/bin/python3"
          - "/root/run_goose.py"
          - "--only-if-empty-db"
          env:
            - name: MF_METADATA_DB_NAME
              value: "metaflow"
            - name: MF_METADATA_DB_PORT
              value: "5432"
            - name: MF_METADATA_DB_PSWD
              value: "metaflow"
            - name: MF_METADATA_DB_USER
              value: "metaflow"
            - name: MF_METADATA_DB_HOST
              value: metaflow-postgresql
      containers:
        - name: metaflow-service
          securityContext:
            {}
          image: "public.ecr.aws/outerbounds/metaflow_metadata_service:v2.4.13"
          command: ["/opt/latest/bin/python3", "-m", "services.metadata_service.server" ]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {}
          env:
            - name: MF_METADATA_DB_NAME
              value: "metaflow"
            - name: MF_METADATA_DB_PORT
              value: "5432"
            - name: MF_METADATA_DB_PSWD
              value: "metaflow"
            - name: MF_METADATA_DB_USER
              value: "metaflow"
            - name: MF_METADATA_DB_HOST
              value: <REDACTED>
---
```

This makes it impossible to work on a PostgreSQL instance which requires TLS. The init container won't be able to start, the error will be similar to this (on an RDS instance, which -by default- requires TLS):
```
psycopg2.OperationalError: connection to server at "<REDACTED>.us-west-2.rds.amazonaws.com" (<REDACTED>), port 5432 failed: FATAL:  no pg_hba.conf entry for host "<REDACTED>", user "metaflow", database "metaflow", no encryption
```
